pipeline
{
    agent any
    environment 
    {
        AWS_ACCOUNT_ID="132737078540"
        AWS_REGION="us-east-1"
        AWS_ECS_CLUSTER='FinalProjectCluster'
        AWS_ECS_SERVICE='Test'
        AWS_ECS_TASK_DEFINITION='FinalProjectFam'
        AWS_ECS_COMPATIBILITY='FARGATE'
        IMAGE_TAG="latest"
        AWS_ECS_NETWORK_MODE='awsvpc'
        IMAGE_NAME="status-page"
        AWS_ECS_CPU='256'
        AWS_ECS_MEMORY='512'
        REPOSITORY_URI="132737078540.dkr.ecr.us-east-1.amazonaws.com/status-page-app-image"
    } 

    stages
    { 
        stage('AWS Log In')
        {
            agent any
            steps
            {
                sh 'echo "Logging in to AWS..."'
                sh 'aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 132737078540.dkr.ecr.us-east-1.amazonaws.com'
            }
        }
        stage("Building Image")
        {
            agent any
            steps
            {   withCredentials([file(credentialsId: 'gitcryptkey', variable: 'CRYPT_KEY')]) 
                {
                sh "git-crypt unlock ${CRYPT_KEY}"
                }
                sh 'echo "Building Docker Image..."'
                sh 'docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ./Status-Page-App'
            }
        }
        stage('Push Image to ECR')
        {
            agent any
            steps
            {
                sh 'echo "Pushing Image to ECR..."'
                sh 'docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${REPOSITORY_URI}:${IMAGE_TAG}'
                sh 'docker push ${REPOSITORY_URI}:${IMAGE_TAG}'
                
            }
        }
        stage('Deploy in ECS') 
        {
            steps 
            {
                sh 'aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 132737078540.dkr.ecr.us-east-1.amazonaws.com'
                updateContainerDefinitionJsonWithImageVersion()
                sh("/usr/local/bin/aws ecs register-task-definition --region ${AWS_ECR_REGION} --family ${AWS_ECS_TASK_DEFINITION} --execution-role-arn ${AWS_ECS_EXECUTION_ROL} --requires-compatibilities ${AWS_ECS_COMPATIBILITY} --network-mode ${AWS_ECS_NETWORK_MODE} --cpu ${AWS_ECS_CPU} --memory ${AWS_ECS_MEMORY} --container-definitions file://${AWS_ECS_TASK_DEFINITION_PATH}")
                def taskRevision = sh(script: "/usr/local/bin/aws ecs describe-task-definition --task-definition ${AWS_ECS_TASK_DEFINITION} | egrep \"revision\" | tr \"/\" \" \" | awk '{print \$2}' | sed 's/\"\$//'", returnStdout: true)
                sh("/usr/local/bin/aws ecs update-service --cluster ${AWS_ECS_CLUSTER} --service ${AWS_ECS_SERVICE} --task-definition ${AWS_ECS_TASK_DEFINITION}:${taskRevision}")
            }
        }
    }
}
